
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xce\x84\x87SFM\xb2\x08X!\xd0\x87\xf5|~E'
    
_lr_action_items = {'PLUS_OP':([1,3,],[4,-2,]),'NUMBER':([0,4,],[3,3,]),'SEMICOLON':([3,5,],[-2,6,]),'$end':([2,6,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,4,],[1,5,]),'expression':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> term PLUS_OP term SEMICOLON','expression',4,'p_expression','parser.py',9),
  ('term -> NUMBER','term',1,'p_term','parser.py',13),
]
