#!/usr/bin/perl
{
	$a=10;
	# These these have not yet been included
	($a == $b) ? $a = 1 : $b = 1;			# http://affy.blogspot.in/p5be/ch04.htm
	#I am just writing some comment
	@b=(1,2,3);

	$b = -19.123e2;
	$c = 10E-3.3;
	$a = $b * $c;
	if (~$a>>1 ^ $b**=1 || $b == $c) {
		# body...
		$c = $a.$b
		$d = 024
		$d = 24
		$d = 087
		$d = 87
		$d = 0xa3
		$d = 0xA123
		$d = 0xFF
		$d = 0xGF
	}

			print ("er\tror\n")
	print ('er\tror\n')
}
